#include<iostream>
using namespace std;

class employees{
	public:
		
	int emp_id;
	string emp_name;
	string emp_roll;
	int emp_age;
	int emp_salary;
	int emp_experiance;	
	string emp_city;
	string emp_company_name;
	
};

main(){
	employees obj1,obj2,obj3,obj4,obj5;
	
	cout<<"enter the emp_id :";
	cin>>obj1.emp_id;
	cout<<"enter the emp_name :";
	cin>>obj1.emp_name;
    cout<<"enter the emp_roll:";
	cin>>obj1.emp_roll;
	cout<<"enter the emp_age :";
	cin>>obj1.emp_age;
	cout<<"enter the emp_salary :";
	cin>>obj1.emp_salary;
	cout<<"enter the emp_experiance :";
	cin>>obj1.emp_experiance;
	cout<<"enter the emp_city :";
	cin>>obj1.emp_city;
	cout<<"enter the emp_company_name :";
	cin>>obj1.emp_company_name;
	
	cout<<"enter the 2 employees details ";
	cout<<"enter the emp_id :";
	cin>>obj2.emp_id;
	cout<<"enter the emp_name :";
	cin>>obj2.emp_name;
    cout<<"enter the emp_roll:";
	cin>>obj2.emp_roll;
	cout<<"enter the emp_age :";
	cin>>obj2.emp_age;
	cout<<"enter the emp_salary :";
	cin>>obj2.emp_salary;
	cout<<"enter the emp_experiance :";
	cin>>obj2.emp_experiance;
	cout<<"enter the emp_city :";
	cin>>obj2.emp_city;
	cout<<"enter the emp_company_name :";
	cin>>obj2.emp_company_name;
	
	
	cout<<"enter the 3 employees details ";
	cout<<"enter the emp_id :";
	cin>>obj3.emp_id;
	cout<<"enter the emp_name :";
	cin>>obj3.emp_name;
    cout<<"enter the emp_roll:";
	cin>>obj3.emp_roll;
	cout<<"enter the emp_age :";
	cin>>obj3.emp_age;
	cout<<"enter the emp_salary :";
	cin>>obj3.emp_salary;
	cout<<"enter the emp_experiance :";
	cin>>obj3.emp_experiance;
	cout<<"enter the emp_city :";
	cin>>obj3.emp_city;
	cout<<"enter the emp_company_name :";
	cin>>obj3.emp_company_name;
	
	cout<<"enter the 4 employees details ";
	cout<<"enter the emp_id :";
	cin>>obj4.emp_id;
	cout<<"enter the emp_name :";
	cin>>obj4.emp_name;
    cout<<"enter the emp_roll:";
	cin>>obj4.emp_roll;
	cout<<"enter the emp_age :";
	cin>>obj4.emp_age;
	cout<<"enter the emp_salary :";
	cin>>obj4.emp_salary;
	cout<<"enter the emp_experiance :";
	cin>>obj4.emp_experiance;
	cout<<"enter the emp_city :";
	cin>>obj4.emp_city;
	cout<<"enter the emp_company_name :";
	cin>>obj4.emp_company_name;
	
	cout<<"enter the 5 employees details ";
	cout<<"enter the emp_id :";
	cin>>obj5.emp_id;
	cout<<"enter the emp_name :";
	cin>>obj5.emp_name;
    cout<<"enter the emp_roll:";
	cin>>obj5.emp_roll;
	cout<<"enter the emp_age :";
	cin>>obj5.emp_age;
	cout<<"enter the emp_salary :";
	cin>>obj5.emp_salary;
	cout<<"enter the emp_experiance :";
	cin>>obj5.emp_experiance;
	cout<<"enter the emp_city :";
	cin>>obj5.emp_city;
	cout<<"enter the emp_company_name :";
	cin>>obj5.emp_company_name;
	
	
	cout<<obj1.emp_id<<endl;
	cout<<obj1.emp_name<<endl;
	cout<<obj1.emp_roll<<endl;
	cout<<obj1.emp_age<<endl;
	cout<<obj1.emp_salary<<endl;
	cout<<obj1.emp_experiance<<endl;
	cout<<obj1.emp_city<<endl;
	cout<<obj1.emp_company_name<<endl;
	
	
	cout<<obj2.emp_id<<endl;
	cout<<obj2.emp_name<<endl;
	cout<<obj2.emp_roll<<endl;
	cout<<obj2.emp_age<<endl;
	cout<<obj2.emp_salary<<endl;
	cout<<obj2.emp_experiance<<endl;
	cout<<obj2.emp_city<<endl;
	cout<<obj2.emp_company_name<<endl;
	
	cout<<obj3.emp_id<<endl;
	cout<<obj3.emp_name<<endl;
	cout<<obj3.emp_roll<<endl;
	cout<<obj3.emp_age<<endl;
	cout<<obj3.emp_salary<<endl;
	cout<<obj3.emp_experiance<<endl;
	cout<<obj3.emp_city<<endl;
	cout<<obj3.emp_company_name<<endl;
	
	cout<<obj4.emp_id<<endl;
	cout<<obj4.emp_name<<endl;
	cout<<obj4.emp_roll<<endl;
	cout<<obj4.emp_age<<endl;
	cout<<obj4.emp_salary<<endl;
	cout<<obj4.emp_experiance<<endl;
	cout<<obj4.emp_city<<endl;
	cout<<obj4.emp_company_name<<endl;
	
	cout<<obj5.emp_id<<endl;
	cout<<obj5.emp_name<<endl;
	cout<<obj5.emp_roll<<endl;
	cout<<obj5.emp_age<<endl;
	cout<<obj5.emp_salary<<endl;
	cout<<obj5.emp_experiance<<endl;
	cout<<obj5.emp_city<<endl;
	cout<<obj5.emp_company_name<<endl;
	
}
	
	
	
	

